<?php

namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();
        Region::insert([
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Aladağ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Ceyhan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Çukurova', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Feke', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'İmamoğlu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Karaisalı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Karataş', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Kozan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Pozantı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Saimbeyli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Sarıçam', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Seyhan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Tufanbeyli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Yumurtalık', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Adana', 'district_name' => 'Yüreğir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Akseki', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Aksu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Alanya', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Demre', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Döşemealtı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Elmalı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Finike', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Gazipaşa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Gündoğmuş', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'İbradı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Kaş', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Kemer', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Kepez', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Konyaaltı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Korkuteli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Kumluca', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Manavgat', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Muratpaşa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Akdeniz', 'city_name' => 'Antalya', 'district_name' => 'Serik', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Aşkale', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Aziziye', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Çat', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Hınıs', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Horasan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'İspir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Karaçoban', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Karayazı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Köprüköy', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Narman', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Oltu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Olur', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Palandöken', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Pasinler', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Pazaryolu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Şenkaya', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Tekman', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Tortum', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Uzundere', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Erzurum', 'district_name' => 'Yakutiye', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Bahçesaray', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Başkale', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Çaldıran', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Çatak', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Edremit', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Erciş', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Gevaş', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Gürpınar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'İpekyolu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Muradiye', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Özalp', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Saray', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Doğu Anadolu', 'city_name' => 'Van', 'district_name' => 'Tuşba', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Aliağa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Balçova', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Bayındır', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Bayraklı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Bergama', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Beydağ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Bornova', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Buca', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Çeşme', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Çiğli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Dikili', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Foça', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Gaziemir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Güzelbahçe', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Karabağlar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Karaburun', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Karşıyaka', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Kemalpaşa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Kınık', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Kiraz', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Konak', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Menderes', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Menemen', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Narlıdere', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Ödemiş', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Seferihisar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Selçuk', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Tire', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Torbalı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'İzmir', 'district_name' => 'Urla', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Bozdoğan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Buharkent', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Çine', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Didim', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Efeler', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Germencik', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'İncirliova', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Karacasu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Karpuzlu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Koçarlı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Köşk', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Kuşadası', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Kuyucak', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Nazilli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Söke', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Sultanhisar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Ege', 'city_name' => 'Aydın', 'district_name' => 'Yenipazar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Gaziantep', 'district_name' => 'Araban', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Gaziantep', 'district_name' => 'İslahiye', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Gaziantep', 'district_name' => 'Karkamış', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Gaziantep', 'district_name' => 'Nizip', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Gaziantep', 'district_name' => 'Nurdağı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Gaziantep', 'district_name' => 'Oğuzeli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Gaziantep', 'district_name' => 'Şahinbey', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Gaziantep', 'district_name' => 'Şehitkamil', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Gaziantep', 'district_name' => 'Yavuzeli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Akçakale', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Birecik', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Bozova', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Ceylanpınar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Eyyübiye', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Halfeti', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Haliliye', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Harran', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Hilvan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Karaköprü', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Siverek', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Suruç', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Güneydoğu Anadolu', 'city_name' => 'Şanlıurfa', 'district_name' => 'Viranşehir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Akyurt', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Altındağ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Ayaş', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Bala', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Beypazarı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Çamlıdere', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Çankaya', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Çubuk', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Elmadağ', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Etimesgut', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Evren', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Gölbaşı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Güdül', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Haymana', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Kahramankazan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Kalecik', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Keçiören', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Kızılcahamam', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Mamak', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Nallıhan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Polatlı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Pursaklar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Sincan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Şereflikoçhisar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Ankara', 'district_name' => 'Yenimahalle', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Ahırlı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Akören', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Akşehir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Altınekin', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Beyşehir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Bozkır', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Cihanbeyli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Çeltik', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Çumra', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Derbent', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Derebucak', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Doğanhisar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Emirgazi', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Ereğli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Güneysınır', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Hadim', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Halkapınar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Hüyük', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Ilgın', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Kadınhanı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Karapınar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Karatay', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Kulu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Meram', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Sarayönü', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Selçuklu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Seydişehir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Taşkent', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Tuzlukçu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Yalıhüyük', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'İç Anadolu', 'city_name' => 'Konya', 'district_name' => 'Yunak', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Adalar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Arnavutköy', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Ataşehir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Avcılar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Bağcılar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Bahçelievler', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Bakırköy', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Başakşehir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Bayrampaşa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Beşiktaş', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Beykoz', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Beylikdüzü', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Beyoğlu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Büyükçekmece', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Çatalca', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Çekmeköy', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Esenler', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Esenyurt', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Eyüpsultan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Fatih', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Gaziosmanpaşa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Güngören', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Kadıköy', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Kağıthane', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Kartal', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Küçükçekmece', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Maltepe', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Pendik', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Sancaktepe', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Sarıyer', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Silivri', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Sultanbeyli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Sultangazi', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Şile', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Şişli', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Tuzla', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Ümraniye', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Üsküdar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'İstanbul', 'district_name' => 'Zeytinburnu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'Edirne', 'district_name' => 'Enez', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'Edirne', 'district_name' => 'Havsa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'Edirne', 'district_name' => 'İpsala', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'Edirne', 'district_name' => 'Keşan', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'Edirne', 'district_name' => 'Lalapaşa', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'Edirne', 'district_name' => 'Meriç', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'Edirne', 'district_name' => 'Merkez', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'Edirne', 'district_name' => 'Süloğlu', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Marmara', 'city_name' => 'Edirne', 'district_name' => 'Uzunköprü', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => '19 Mayıs', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Alaçam', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Asarcık', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Atakum', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Ayvacık', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Bafra', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Canik', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Çarşamba', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Havza', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'İlkadım', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Kavak', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Ladik', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Salıpazarı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Tekkeköy', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Terme', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Vezirköprü', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Samsun', 'district_name' => 'Yakakent', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Akçaabat', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Araklı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Arsin', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Beşikdüzü', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Çarşıbaşı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Çaykara', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Dernekpazarı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Düzköy', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Hayrat', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Köprübaşı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Maçka', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Of', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Ortahisar', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Sürmene', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Şalpazarı', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Tonya', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Vakfıkebir', 'created_at' => $now, 'updated_at' => $now],
            ['name' => 'Karadeniz', 'city_name' => 'Trabzon', 'district_name' => 'Yomra', 'created_at' => $now, 'updated_at' => $now],
        ]);
    }
}
